### ISSUE TITLE
Build errors during cmake with -DENABLE_CUFFT_BACKEND=True

### ISSUE THREAD

**Issue by vidyalatha-badde** [oneapi-src/oneMKL#321] opened 2023-05-18 07:31 UTC
Could someone help me with installing oneMKL with cufft?

Cmake --version: 3.16.3
Using open source dpcpp compiler: clang version 17.0.0

`**cmake .. -DCMAKE_CXX_COMPILER=/home/tcs/sycl_workspace/llvm/build/bin/clang++ -DCMAKE_C_COMPILER=/home/tcs/sycl_workspace/llvm/build/bin/clang -DENABLE_CUFFT_BACKEND=True -DENABLE_MKLCPU_BACKEND=False -DENABLE_MKLGPU_BACKEND=False**

-- CMAKE_BUILD_TYPE: Release
-- TARGET_DOMAINS: dft
-- Looking for dpc++
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "11.6")
-- Performing Test IS_SUPPORTED
-- Performing Test IS_SUPPORTED - Success
-- The C compiler identification is Clang 17.0.0
-- Check for working C compiler: /home/tcs/sycl_workspace/llvm/build/bin/clang
-- Check for working C compiler: /home/tcs/sycl_workspace/llvm/build/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /opt/intel/oneapi/intelpython/latest/bin/python (found version "3.9.12")
-- SYCL_DEVICE_FILTER will be set to the following value(s): [gpu] for run-time dispatching examples
-- Configuring done
CMake Error at src/dft/backends/cufft/CMakeLists.txt:25 (add_library):
  Target "onemkl_dft_cufft" links to target "CUDA::cufft" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/dft/backends/cufft/CMakeLists.txt:25 (add_library):
  Target "onemkl_dft_cufft" links to target "CUDA::cuda_driver" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/dft/backends/cufft/CMakeLists.txt:25 (add_library):
  Target "onemkl_dft_cufft" links to target "CUDA::cufft" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/dft/backends/cufft/CMakeLists.txt:25 (add_library):
  Target "onemkl_dft_cufft" links to target "CUDA::cuda_driver" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at src/dft/backends/cufft/CMakeLists.txt:26 (add_library):
  Target "onemkl_dft_cufft_obj" links to target "CUDA::cufft" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

CMake Error at src/dft/backends/cufft/CMakeLists.txt:26 (add_library):
  Target "onemkl_dft_cufft_obj" links to target "CUDA::cuda_driver" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by FMarno** [comment] 2023-05-18 08:18
Hi @vidyalatha-badde,
Currently we are using [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html) to get the CUDA dependencies. I realise now that this was only introduced in CMake 3.17, so we either need to change how the CUDA libraries are linked or up the `cmake_minimum_required`.
For now, would you be able to try using a version of cmake >= 3.17 to see if that works for you?
Thanks

**Comment by vidyalatha-badde** [comment] 2023-05-18 08:37
Thanks, @FMarno for the suggestion. I'll give it a try and get back to you.

**Comment by vidyalatha-badde** [comment] 2023-05-19 11:03
Hi @FMarno ,

Is there any alternative other than updating the cmake version?

**Comment by FMarno** [comment] 2023-05-19 12:31
@vidyalatha-badde You can update the cmake to use [FindCUDA](https://cmake.org/cmake/help/latest/module/FindCUDA.html). If you can wait then I'll be doing this pretty soon.

**Comment by vidyalatha-badde** [comment] 2023-05-19 14:16
Hello @FMarno,

Thanks for responding.
I found a machine where the cmake version is 3.22.1. Now I'm able to build it successfully but during the
 `cmake --install . --prefix <path_to_install_dir>` step I'm getting the following error. 
```
-- Installing: /home/tcs2/vidya/oneMKL/build/./lib/cmake/oneMKL/oneMKLTargets.cmake
-- Installing: /home/tcs2/vidya/oneMKL/build/./lib/cmake/oneMKL/oneMKLTargets-release.cmake
-- Installing: /home/tcs2/vidya/oneMKL/build/./lib/cmake/oneMKL/oneMKLConfig.cmake
-- Installing: /home/tcs2/vidya/oneMKL/build/./lib/cmake/oneMKL/oneMKLConfigVersion.cmake
CMake Error at cmake/cmake_install.cmake:46 (file):
  file INSTALL cannot find "/home/tcs2/vidya/oneMKL/cmake/FindMKL.cmake": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:77 (include)
```
could you please help me out in fixing this issue?

Thanks,
Vidya

**Comment by FMarno** [comment] 2023-05-19 15:32
Hi @vidyalatha-badde,
I think this might be caused by https://github.com/oneapi-src/oneMKL/pull/316.
I'm not really sure of the solution, but maybe change `FindMKL` to `MKLConfig` here https://github.com/oneapi-src/oneMKL/blob/develop/cmake/CMakeLists.txt#L20.

@mkrainiuk could you please advise?

**Comment by vidyalatha-badde** [comment] 2023-05-19 16:40
Hi @FMarno ,

I tried your suggestion replacing **FindMKL with oneMKLConfig** instead of MKLConfig **worked**.

**Comment by FMarno** [comment] 2023-05-19 16:43
@vidyalatha-badde good to hear. I've created a PR to allow the linking to work with earlier versions of cmake #323. Unfortunately this won't fix the `FindMKL`/`MKLConfig` problem, I think that will be a different PR.

**Comment by mkrainiuk** [comment] 2023-05-19 16:47
Thanks for investigating it! I'm preparing changes for the missed FindMKL.

**Comment by vidyalatha-badde** [comment] 2023-05-19 16:47
Ok, that's great. Thanks for your time @FMarno

**Comment by vidyalatha-badde** [comment] 2023-05-19 17:07
@FMarno Here is another issue maybe it is not related to this question, but when trying to use open-source onemkl for fft I'm getting this particular error during runtime
 ```
terminate called after throwing an instance of 'oneapi::mkl::exception'
  what():  oneMKL: dft/backends/cufft/clean_plans: Failed to change cuda context.
Aborted (core dumped)
```
If you want I can raise a new issue. Please let me know

**Comment by FMarno** [comment] 2023-05-19 17:31
@vidyalatha-badde I would appreciate it if you could open a new issue and I'll investigate after the weekend. If you can include a minimal reproducer then that would be very helpful!

**Comment by FMarno** [comment] 2023-05-22 14:56
> @FMarno Here is another issue maybe it is not related to this question, but when trying to use open-source onemkl for fft I'm getting this particular error during runtime
> 
> ```
> terminate called after throwing an instance of 'oneapi::mkl::exception'
>  what():  oneMKL: dft/backends/cufft/clean_plans: Failed to change cuda context.
> Aborted (core dumped)
> ```
> 
> If you want I can raise a new issue. Please let me know

@vidyalatha-badde I tried running the tests but didn't see any issues. Have you run the tests? you could try running `<build_folder>/bin/test_main_dft_rt`.

**Closed as completed** 2023-05-24 05:20 UTC
Labels: question
