### ISSUE TITLE
[cuBLAS] cuBLAS test sometimes segfaults with dpc++ and hipSYCL

### ISSUE THREAD

**Issue by nilsfriess** [oneapi-src/oneMKL#245] opened 2022-11-02 13:48 UTC
# Summary
When trying to run the unit tests from the cuBLAS backend, one test case sometimes causes a segfault both when using hipSYCL and dpc++.

# Version
For the dpc++ tests, I used the current develop branch (b8ec0cf). For the tests with hipSYCL 7020ba92e72f27850d8812512a1e737c3e446c2e was used (the cuBLAS backend does not compile with hipSYCL when using the current oneMKL develop branch, the branch I used here has the changes to make it compile again; it is simply a library that oneMKL should be linked against when compiling with hipSYCL that is missing in one of the CMake files).

# Environment
* Hardware: NVIDIA GeForce GTX 1080
* CUDA 11.6
* Ubuntu 20.04
* dpc++: intel/llvm@8ca7d50456bde7f144eb5779bc6131bae841c1bb with CUDA support (see compile instructions below)
* hipSYCL: illuhad/hipSYCL@012e16d6d3d57330c176d7d536f657b0d8a9a197 compiled with CUDA backend enabled
* CMake Output:
    * [cmake_dpcpp.log](https://github.com/oneapi-src/oneMKL/files/9920662/cmake_dpcpp.log)
    * [cmake_hipSYCL.log](https://github.com/oneapi-src/oneMKL/files/9920663/cmake_hipSYCL.log)

# Steps to reproduce
Install dpc++ with CUDA support as described [here](https://intel.github.io/llvm-docs/GetStartedGuide.html), i.e., run (with the paths of course adapted)
```
CUDA_LIB_PATH=/usr/local/cuda-11.6/lib64/stubs/ CC=/usr/lib/llvm-14/bin/clang CXX=/usr/lib/llvm-14/bin/clang++ python ../buildbot/configure.py --cuda --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.6"
CUDA_LIB_PATH=/usr/local/cuda-11.6/lib64/stubs/ CC=/usr/lib/llvm-14/bin/clang CXX=/usr/lib/llvm-14/bin/clang++ python ../buildbot/compile.py -j64
```
Then build oneMKL with the cuBLAS backend as described in the documentation, i.e., run 
```
cmake .. -DCMAKE_CXX_COMPILER=/root/llvm/build/bin/clang++ -DCMAKE_C_COMPILER=/root/llvm/build/bin/clang -DCMAKE_LIBRARY_PATH="/usr/local/cuda-11.6/lib64/stubs" -DENABLE_CUBLAS_BACKEND=True -DENABLE_CURAND_BACKEND=False -DENABLE_ROCRAND_BACKEND=False -DENABLE_ROCBLAS_BACKEND=False -DENABLE_MKLCPU_BACKEND=False -DENABLE_MKLGPU_BACKEND=False -DTARGET_DOMAINS=blas -DREF_BLAS_ROOT=/root/.local/lapack/
```
Possibly, the environment variable `LD_LIBRARY_PATH` has to be adapted to point to the correct llvm and oneMKL library files. Then run
```
make -j64
```
For hipSYCL, a similar setup is used (the llvm compiler is of course not required and the cmake command to compile oneMKL has to be changed accordingly).

# Observed behavior
All but one tests pass (or are skipped). Running 
```
./bin/test_main_blas_rt --gtest_filter="*ImatcopyBatchStrideTests*"
```
after building the test executables as described above sometimes produces the following output
```
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealSinglePrecision/Column_Major_GeForce_GTX_1080_Ti
[  SKIPPED ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealSinglePrecision/Column_Major_GeForce_GTX_1080_Ti (91 ms)
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealSinglePrecision/Row_Major_GeForce_GTX_1080_Ti
[  SKIPPED ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealSinglePrecision/Row_Major_GeForce_GTX_1080_Ti (1 ms)
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealDoublePrecision/Column_Major_GeForce_GTX_1080_Ti
[  SKIPPED ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealDoublePrecision/Column_Major_GeForce_GTX_1080_Ti (0 ms)
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealDoublePrecision/Row_Major_GeForce_GTX_1080_Ti
[  SKIPPED ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.RealDoublePrecision/Row_Major_GeForce_GTX_1080_Ti (0 ms)
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.ComplexSinglePrecision/Column_Major_GeForce_GTX_1080_Ti
[  SKIPPED ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.ComplexSinglePrecision/Column_Major_GeForce_GTX_1080_Ti (1 ms)
[ RUN      ] ImatcopyBatchStrideTestSuite/ImatcopyBatchStrideTests.ComplexSinglePrecision/Row_Major_GeForce_GTX_1080_Ti
free(): invalid pointer
Aborted
```
Sometimes no segfault occurs and all 8 tests are skipped (with the setup described above). When specifying a subset of the tests above, e.g. `--gtest_filter="*ImatcopyBatchStrideTests.ComplexDoublePrecision*"`, no segfaults seem to occur.

# Expected behavior
The test is expected to never cause a segfault.

**Comment by andrewtbarker** [comment] 2022-11-03 16:04
Thank you for reporting this. Can you clarify "sometimes"? How many times do you have to run tests before you see this behavior?

**Comment by nilsfriess** [comment] 2022-11-03 16:10
I can try to measure it more precisely but I would estimate that about 50% of the time, the test segfaults. So running the tests over and over again could produce something like this: fails, passes, passes, fails, fails, fails, passes etc. Let me know if you need more details.

**Comment by andrewtbarker** [comment] 2022-11-07 18:52
I'm having trouble reproducing this locally, I think because of some configuration / compatibility issues with CUDA and the compiler, but I'm working on it. Is there any chance you could build a debug build and run it through valgrind to see if there's a useful trace on the segfault? I realize that could take some time and effort but it might be informative.

**Comment by nilsfriess** [comment] 2022-11-10 15:05
I tried to run valgrind but it just took too long so I started to delete parts of the test to find out which part could cause the segfault. It seems that it is not really a onemkl bug that causes the segfault: if I replace the `test` function of the [file that contains the test](https://github.com/oneapi-src/oneMKL/blob/develop/tests/unit_tests/blas/batch/imatcopy_batch_stride.cpp) by
```
template <typename fp>
int test(device *dev, oneapi::mkl::layout layout, int64_t batch_size) {
    int64_t m = 20;
    int64_t n = 30;
    int64_t lda = std::max(m, n);
    int64_t ldb = std::max(m, n);
    fp alpha = 1.0;
    oneapi::mkl::transpose trans = oneapi::mkl::transpose::N;

    int64_t stride = 1;
    vector<fp, allocator_helper<fp, 64>> AB(stride * batch_size);

    // Call reference IMATCOPY_BATCH_STRIDE.
    imatcopy_ref(layout, trans, m, n, alpha, AB.data(), lda, ldb);

    return 1;
}
```
it still segfaults (and now it also segfaults always not just randomly). If I remove the custom allocator when constructing the vector `AB`, it works fine. So it might actually be something in the `allocator_helper.hpp` that causes the problem.

**Comment by andrewtbarker** [comment] 2022-11-10 16:03
Thank you @nilsfriess , this is very helpful information!

**Comment by andrewtbarker** [comment] 2022-11-10 23:05
> `    int64_t stride = 1;`

Unfortunately I think this line in your reproducer is causing the segfault - the stride here should be 30*30=900. When I set that as the stride I don't get a segfault anymore. I suspect this is different from whatever caused the original issue.

**Comment by andrewtbarker** [comment] 2023-01-11 23:39
I finally got around to trying to reproduce this with a recent LLVM compiler and a non-ancient CUDA (11.8) and I cannot reproduce it - I ran the tests many times with no failures. At this point I am inclined to close it unless there are objections.

**Closed as completed** 2023-02-01 17:32 UTC
