### ISSUE TITLE
when I update the apt source,the error appears 

### ISSUE THREAD

**Issue by anchao1997** [oneapi-src/oneMKL#391] opened 2023-10-01 15:07 UTC
"
Err:9 https://apt.repos.intel.com/intelpython binary/ InRelease                
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Hit:12 https://apt.repos.intel.com/ipp all InRelease                           
Err:11 https://apt.repos.intel.com/mkl all InRelease                           
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Err:12 https://apt.repos.intel.com/ipp all InRelease                           
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Hit:13 https://apt.repos.intel.com/tbb all InRelease                           
Err:13 https://apt.repos.intel.com/tbb all InRelease                           
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Hit:14 https://apt.repos.intel.com/daal all InRelease                          
Err:14 https://apt.repos.intel.com/daal all InRelease                          
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Hit:15 https://apt.repos.intel.com/mpi all InRelease                           
Err:15 https://apt.repos.intel.com/mpi all InRelease                           
  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
Err:16 http://archive.ubuntukylin.com:10006/ubuntukylin xenial InRelease       
  Could not connect to archive.ubuntukylin.com:10006 (124.126.103.228), connection timed out
Reading package lists... Done                               
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/intelpython binary/ InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/ipp all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/tbb all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/daal all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.repos.intel.com/mpi all InRelease: The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/intelpython/binary/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/mkl/dists/all/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/ipp/dists/all/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/tbb/dists/all/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/daal/dists/all/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch https://apt.repos.intel.com/mpi/dists/all/InRelease  The following signatures were invalid: EXPKEYSIG ACFA9FC57E6C5DBE Intel(R) Software Development Products
W: Failed to fetch http://archive.ubuntukylin.com:10006/ubuntukylin/dists/xenial/InRelease  Could not connect to archive.ubuntukylin.com:10006 (124.126.103.228), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
"

and I used the newest GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB, the same appears with the command "sudo wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list"
Does this list "intelproducts.list" contains ACFA9FC57E6C5DBE which results the error?

I firstly install the mkl with the guide "https://www.intel.com/content/www/us/en/developer/articles/guide/installing-free-libraries-and-python-apt-repo.html"

**Comment by andrewtbarker** [comment] 2023-11-22 17:04
I think this is a duplicate of #390

**Closed as completed** 2023-11-27 15:33 UTC
Labels: question
